# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: docker-manager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='docker-manager.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x64ocker-manager.proto\"P\n\x17\x43ontainerManagerRequest\x12\x13\n\x0b\x63ontainerId\x18\x01 \x01(\t\x12 \n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x10.ContainerAction\"?\n\x18\x43ontainerManagerResponse\x12\x13\n\x0b\x63ontainerId\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t*=\n\x0f\x43ontainerAction\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x12\x0c\n\x08RECREATE\x10\x02\x12\n\n\x06STATUS\x10\x03\x32Z\n\x10\x43ontainerManager\x12\x46\n\x0fManageContainer\x12\x18.ContainerManagerRequest\x1a\x19.ContainerManagerResponseb\x06proto3'
)

_CONTAINERACTION = _descriptor.EnumDescriptor(
  name='ContainerAction',
  full_name='ContainerAction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RECREATE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=171,
  serialized_end=232,
)
_sym_db.RegisterEnumDescriptor(_CONTAINERACTION)

ContainerAction = enum_type_wrapper.EnumTypeWrapper(_CONTAINERACTION)
UP = 0
DOWN = 1
RECREATE = 2
STATUS = 3



_CONTAINERMANAGERREQUEST = _descriptor.Descriptor(
  name='ContainerManagerRequest',
  full_name='ContainerManagerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='containerId', full_name='ContainerManagerRequest.containerId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='ContainerManagerRequest.action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=104,
)


_CONTAINERMANAGERRESPONSE = _descriptor.Descriptor(
  name='ContainerManagerResponse',
  full_name='ContainerManagerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='containerId', full_name='ContainerManagerResponse.containerId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='ContainerManagerResponse.result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=169,
)

_CONTAINERMANAGERREQUEST.fields_by_name['action'].enum_type = _CONTAINERACTION
DESCRIPTOR.message_types_by_name['ContainerManagerRequest'] = _CONTAINERMANAGERREQUEST
DESCRIPTOR.message_types_by_name['ContainerManagerResponse'] = _CONTAINERMANAGERRESPONSE
DESCRIPTOR.enum_types_by_name['ContainerAction'] = _CONTAINERACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContainerManagerRequest = _reflection.GeneratedProtocolMessageType('ContainerManagerRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINERMANAGERREQUEST,
  '__module__' : 'docker_manager_pb2'
  # @@protoc_insertion_point(class_scope:ContainerManagerRequest)
  })
_sym_db.RegisterMessage(ContainerManagerRequest)

ContainerManagerResponse = _reflection.GeneratedProtocolMessageType('ContainerManagerResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINERMANAGERRESPONSE,
  '__module__' : 'docker_manager_pb2'
  # @@protoc_insertion_point(class_scope:ContainerManagerResponse)
  })
_sym_db.RegisterMessage(ContainerManagerResponse)



_CONTAINERMANAGER = _descriptor.ServiceDescriptor(
  name='ContainerManager',
  full_name='ContainerManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=234,
  serialized_end=324,
  methods=[
  _descriptor.MethodDescriptor(
    name='ManageContainer',
    full_name='ContainerManager.ManageContainer',
    index=0,
    containing_service=None,
    input_type=_CONTAINERMANAGERREQUEST,
    output_type=_CONTAINERMANAGERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONTAINERMANAGER)

DESCRIPTOR.services_by_name['ContainerManager'] = _CONTAINERMANAGER

# @@protoc_insertion_point(module_scope)
